spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
      pool-name: H2_DB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibername.dialect.H2Dialect
    open-in-view: false
logging:
  level:
    com.example.membership: debug